# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: 
title: Artifical Future

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Blog Posts

description: Stylish Jekyll Theme
author:
  name: Kroum Klutchkov
  email: kroum.klutchkov@gmail.com
  github: Astr-o
  #twitter: dbtek
  #pinterest: asd123
  linkedin: kklutchkov
  stackoverflow: 2907286
  bio: > 
    I love solving real world problems with Data, AI and Machine Learning. Here's some cool stuff I found along the way.
  jobtitle: Software Engineer

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
